config/routes.rb
Rails.application.routes.draw do
  resources :dumies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dumy.rb
class Dumy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dumies_controller.rb
class DumiesController < ApplicationController
  before_action :set_dumy, only: [:show, :edit, :update, :destroy]

  # GET /dumies
  # GET /dumies.json
  def index
    @dumies = Dumy.all
  end

  # GET /dumies/1
  # GET /dumies/1.json
  def show
  end

  # GET /dumies/new
  def new
    @dumy = Dumy.new
  end

  # GET /dumies/1/edit
  def edit
  end

  # POST /dumies
  # POST /dumies.json
  def create
    @dumy = Dumy.new(dumy_params)

    respond_to do |format|
      if @dumy.save
        format.html { redirect_to @dumy, notice: 'Dumy was successfully created.' }
        format.json { render :show, status: :created, location: @dumy }
      else
        format.html { render :new }
        format.json { render json: @dumy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dumies/1
  # PATCH/PUT /dumies/1.json
  def update
    respond_to do |format|
      if @dumy.update(dumy_params)
        format.html { redirect_to @dumy, notice: 'Dumy was successfully updated.' }
        format.json { render :show, status: :ok, location: @dumy }
      else
        format.html { render :edit }
        format.json { render json: @dumy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dumies/1
  # DELETE /dumies/1.json
  def destroy
    @dumy.destroy
    respond_to do |format|
      format.html { redirect_to dumies_url, notice: 'Dumy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dumy
      @dumy = Dumy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dumy_params
      params.fetch(:dumy, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dumies_helper.rb
module DumiesHelper
end

app/views/dumies/_form.html.erb
<%= form_with(model: dumy, local: true) do |form| %>
  <% if dumy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dumy.errors.count, "error") %> prohibited this dumy from being saved:</h2>

      <ul>
      <% dumy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dumies/edit.html.erb
<h1>Editing Dumy</h1>

<%= render 'form', dumy: @dumy %>

<%= link_to 'Show', @dumy %> |
<%= link_to 'Back', dumies_path %>

app/views/dumies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hello world</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dumies.each do |dumy| %>
      <tr>
        <td><%= link_to 'Show', dumy %></td>
        <td><%= link_to 'Edit', edit_dumy_path(dumy) %></td>
        <td><%= link_to 'Destroy', dumy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dumy', new_dumy_path %>

app/views/dumies/new.html.erb
<h1>New Dumy</h1>

<%= render 'form', dumy: @dumy %>

<%= link_to 'Back', dumies_path %>

app/views/dumies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dumy_path(@dumy) %> |
<%= link_to 'Back', dumies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AkashProj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>